set -ex
python3 /home/xinyi/test1/train_hcp2.py \
--dataroot /home/data/HCP \
--checkpoints_dir ./checkpoints3 \
--name HCP99_2 \
--model lesion_inpaint \
--input_nc 45 \
--output_nc 45 \
--init_type kaiming \
--dataset_mode hcp \
--num_threads 0 \
--batch_size 2 \
--beta1 0.99 \
--lr 0.01 \
--n_epochs 50 \
--print_freq 100 \
--save_latest_freq 1000 \
--save_epoch_freq 50 \
--gpu_ids 1 \
--conv_type gate_unet \